### PR TITLE
Prp updates

### PR DESCRIPTION
**Pull request by dimm0**
Thanks for the great chart! Sending some updates I've done when deployed to my cluster

### CODE REVIEW

**Comment by duhow** [comment]
Hi! Thanks for your pull request.
Can you detail what's the purpose of having a `secret` boolean in here?

**Comment by dimm0** [comment]
In my case I'm using TLS, but there's a default cert provided for all ingresses, so I don't need to specify an additional secret.

Actually I was wondering why you're using this way to set up ingress... The standard way in helm template (the one you get with "helm create") looks more convenient to me

**Comment by duhow** [comment]
The reason for the change from default Helm Chart is because it is not generally expected having multiple hostnames pointing to same Ingress. Also I'm trying to keep similar syntax as Bitnami charts do.

If you think this chart deserves having multiple hostnames, we can prepare to do so.

**Comment by dimm0** [comment]
Can you make the secret optional? It’s not always needed...

**Pull request merged**
